name: gemini_app
description: "A new Flutter project."
publish_to: "none"
version: 0.2.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.0
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  internet_connection_checker: ^1.0.0+1
  pdf: ^3.10.8
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  external_path: ^1.0.3
  image: ^4.1.7
  media_scanner: ^2.1.0
  local_auth: ^2.2.0
  fluttertoast: ^8.2.6
  # dependencies for To-Do app
  # flutter_svg: ^2.0.10+1 # already exists
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  intl: ^0.19.0
  # dependencies for whatsapp status saver
  # permission_handler: ^10.4.1
  # provider: ^6.0.5
  path_provider: ^2.0.11
  image_gallery_saver: ^2.0.2
  video_player: ^2.7.0
  chewie: ^1.5.0
  share_plus: ^7.0.2
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/animation/
