name: gemini_app
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.0
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  internet_connection_checker: ^1.0.0+1
  pdf: ^3.10.8
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  external_path: ^1.0.3
  image: ^4.1.7
  media_scanner: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/animation/
